apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: argocd-attach.fling.vsphere.vmware.com.2.0.3
spec:
  refName: argocd-attach.fling.vsphere.vmware.com
  releasedAt: "2025-10-01T19:05:40Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/warroyo/argocd-attach-service@sha256:11adc8dc51867bf44d4eb803e958eb5e01a5fb4cdb29b3c4f2820805be251d20
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        blocked_namespaces:
          default: []
          items:
            default: ""
            type: string
          type: array
        namespace:
          default: ""
          type: string
        resync_period:
          default: "60"
          type: string
      type: object
  version: 2.0.3
