apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: argocd-attach.fling.vsphere.vmware.com.2.0.0
spec:
  refName: argocd-attach.fling.vsphere.vmware.com
  releasedAt: "2025-10-01T18:28:55Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/warroyo/argocd-attach-service@sha256:b47d654c56374fac0411b6468b763010431f06aec355f11e7e840c8c36af7938
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        blocked_namespaces:
          default: []
          items:
            default: ""
            type: string
          type: array
        namespace:
          default: ""
          type: string
        resync_period:
          default: "60"
          type: string
      type: object
  version: 2.0.0
