apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: argocd-attach.fling.vsphere.vmware.com
spec:
  displayName: ArgoCD Attach Service
  longDescription: Provides the ability to auto attach clusters to ArgoCD
  shortDescription: ArgoCD Auto Attach

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: argocd-attach.fling.vsphere.vmware.com.2.0.5
spec:
  refName: argocd-attach.fling.vsphere.vmware.com
  releasedAt: "2025-10-01T19:45:39Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/warroyo/argocd-attach-service@sha256:869721c9bdd60f4d6eb1973d179e093db7a641af784db8bd8f9d55c800dc34eb
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        blocked_namespaces:
          default: []
          items:
            default: ""
            type: string
          type: array
        namespace:
          default: ""
          type: string
        resync_period:
          default: "60"
          type: string
      type: object
  version: 2.0.5
