apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: argocd-attach.fling.vsphere.vmware.com.0.0.0
spec:
  refName: argocd-attach.fling.vsphere.vmware.com
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - git: {}
      template:
      - ytt:
          paths:
          - config
      - kbld: {}
  valuesSchema:
    openAPIv3: null
  version: 0.0.0

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: argocd-attach.fling.vsphere.vmware.com
spec:
  displayName: argocd-attach
  longDescription: argocd-attach.fling.vsphere.vmware.com
  shortDescription: argocd-attach.fling.vsphere.vmware.com

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: null
  name: argocd-attach
spec:
  packageRef:
    refName: argocd-attach.fling.vsphere.vmware.com
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: argocd-attach-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
