---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-attach-sync
  namespace: {{ include "metacontroller.namespace" . }}
data:
  sync.py: |-
    {{ .Files.Get "controller-code/sync.py" | nindent 4 }} 
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-attach-controller
  namespace: {{ include "metacontroller.namespace" . }}
spec:
  ports:
  - port: 80
  selector:
    app: argocd-attach-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-attach-controller
  namespace: {{ include "metacontroller.namespace" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-attach-controller
  template:
    metadata:
      labels:
        app: argocd-attach-controller
    spec:
      containers:
        command: ["/bin/sh","-c"]
        args: ["pip install yaml; python /hooks/sync.py"]
        image: {{ .Values.python_image }}
        name: controller
        env:
        - name: ARGO_NS
          value: {{ .Values.argo_namespace }}
        volumeMounts:
        - mountPath: /hooks
          name: hooks
      volumes:
      - configMap:
          name: argocd-attach-sync
        name: hooks
---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: argocd-attach-cluster
  namespace:  {{ include "metacontroller.namespace" . }}
spec:
  attachments:
  - apiVersion: v1
    resource: secrets
    updateStrategy:
      method: InPlace
  hooks:
    customize:
      webhook:
        url: http://argocd-attach-controller/customize
    sync:
      webhook:
        url: http://argocd-attach-controller/sync
  resources:
  - apiVersion: cluster.x-k8s.io/v1beta1
    resource: clusters
  resyncPeriodSeconds: 60