apiVersion: field.vmware.com/v1
kind: ArgoNamespace
metadata:
  name: sample-ns
spec:
  argoNamespace: "argocd"
  serviceAccount: "" # optionally use existing SA
  clusterLabels:
    test: "test"
    test2: "test3"
  project: default